"use client";
import { FormEvent, useState } from "react";
const services = [["01","Sistemas web","Plataformas hechas a medida para que la operación diaria deje de depender de hojas sueltas y mensajes."],["02","Presencia institucional","Sitios web claros, rápidos y administrables que presentan su organización con la seriedad que merece."],["03","Estrategia y marketing","Una propuesta digital coherente: contenido, identidad visual y campañas orientadas a resultados medibles."]];
const projects = [["Gestión académica","Control estudiantil","Flujos de registro, consulta y seguimiento pensados para instituciones educativas."],["Organización","Sistema de horarios","Información ordenada y accesible para estudiantes, docentes y coordinación."],["Presencia profesional","Estudio jurídico","Una web institucional que comunica confianza, servicios y vías de contacto."]];
export default function Home() { const [sent,setSent]=useState(false); function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSent(true)} return <main>
<nav className="nav wrap"><a className="brand" href="#inicio" aria-label="Nexo Digital, inicio"><i>N</i><span>Nexo<br/>Digital</span></a><div className="nav-links"><a href="#servicios">Servicios</a><a href="#proyectos">Proyectos</a><a href="#enfoque">Enfoque</a></div><a className="nav-contact" href="#contacto">Hablemos <b>↗</b></a></nav>
<section id="inicio" className="hero wrap"><div className="hero-copy reveal"><p className="eyebrow">Estudio digital · Ecuador</p><h1>Soluciones que<br/><em>ordenan</em> el trabajo<br/>y elevan su presencia.</h1><p className="hero-text">Diseñamos sistemas, sitios web y estrategia digital para organizaciones que buscan avanzar con claridad.</p><a className="button" href="#contacto">Cuéntenos su proyecto <span>→</span></a></div><div className="hero-art reveal delay"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="monogram">N<span>·</span>D</div><div className="art-caption"><span>Desarrollo + estrategia</span><span>2026</span></div></div></section>
<section className="intro wrap reveal"><p className="eyebrow">Nuestro punto de partida</p><p className="statement">La tecnología no tiene que sentirse complicada. Debe responder con precisión a lo que su equipo, sus estudiantes o sus clientes necesitan hacer.</p></section>
<section id="servicios" className="services wrap"><div className="section-head reveal"><p className="eyebrow">Lo que hacemos</p><h2>Diseño digital<br/>con propósito.</h2></div><div className="service-list">{services.map(([number,title,description],index)=><article className={`service reveal delay-${index}`} key={title}><span>{number}</span><div><h3>{title}</h3><p>{description}</p></div><b>↗</b></article>)}</div></section>
<section id="proyectos" className="work"><div className="wrap"><div className="section-head light reveal"><p className="eyebrow">Experiencia aplicable</p><h2>Proyectos que ya<br/>resuelven.</h2></div><div className="project-grid">{projects.map(([type,title,description],index)=><article className={`project reveal delay-${index}`} key={title}><div className={`project-visual visual-${index}`}><span>{String(index+1).padStart(2,"0")}</span><strong>{index===0?"{ }":index===1?"09:30":"§"}</strong></div><p className="project-type">{type}</p><h3>{title}</h3><p className="project-description">{description}</p></article>)}</div></div></section>
<section id="enfoque" className="approach wrap"><div className="approach-card reveal"><p className="eyebrow">Una colaboración directa</p><h2>Dos desarrolladores.<br/>Un compromiso claro.</h2><p>Francisco Ríos y Kevin Pedrera combinan formación en desarrollo de software y experiencia práctica en proyectos institucionales. Trabajamos de forma remota, con comunicación constante y entregas que se pueden revisar.</p><div className="principles"><span>01 · Diagnóstico honesto</span><span>02 · Proceso visible</span><span>03 · Solución mantenible</span></div></div></section>
<section id="contacto" className="contact wrap"><div className="contact-copy reveal"><p className="eyebrow">Iniciemos una conversación</p><h2>Su siguiente<br/><em>avance</em> comienza aquí.</h2><p>Cuéntenos brevemente qué necesita. Le responderemos para entender el contexto y proponer el camino más adecuado.</p><p className="remote-note">Atención remota · Ecuador y Latinoamérica</p></div><form className="reveal delay" onSubmit={submit}>{sent?<div className="success"><span>✓</span><h3>Gracias por escribirnos.</h3><p>Recibimos su solicitud. Le responderemos pronto para conversar sobre su proyecto.</p><button type="button" onClick={()=>setSent(false)}>Enviar otra consulta</button></div>:<><label>Nombre<input required name="name" placeholder="¿Cómo le llamamos?"/></label><label>Correo electrónico<input required type="email" name="email" placeholder="nombre@organizacion.com"/></label><label>¿En qué podemos ayudarle?<select name="service" defaultValue=""><option value="" disabled>Seleccione una opción</option><option>Sistema web a medida</option><option>Sitio web institucional</option><option>Estrategia y marketing digital</option><option>Otro proyecto</option></select></label><label>Cuéntenos un poco<textarea required name="message" placeholder="Objetivo, contexto o idea inicial..." rows={4}/></label><button className="button submit" type="submit">Enviar consulta <span>→</span></button></>}</form></section>
<footer className="wrap"><a className="brand" href="#inicio"><i>N</i><span>Nexo Digital</span></a><p>Desarrollo web y estrategia digital</p><a href="#inicio">Volver arriba ↑</a></footer></main> }
